-- ========================================================
-- ARANDU CLOUD: Esquema SQL para Supabase
-- Puedes pegar todo este código en el "SQL Editor" de Supabase
-- y presionar "Run" para crear tu base de datos al instante.
-- ========================================================

-- 1. Crear tabla 'signals' para almacenar las señales de TradingView
CREATE TABLE public.signals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    direction TEXT NOT NULL,          -- 'BUY' o 'SELL'
    price NUMERIC NOT NULL,
    kill_zone TEXT,
    in_killzone BOOLEAN DEFAULT FALSE,
    status TEXT DEFAULT 'PENDING',    -- Estados: 'PENDING', 'EXECUTED', 'ERROR'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Habilitar Seguridad de Nivel de Fila (RLS)
ALTER TABLE public.signals ENABLE ROW LEVEL SECURITY;

-- 3. Crear política para permitir que tu servidor Node y tu bot MQL5 puedan Leer/Escribir
-- (Para este setup automático, permitimos acceso usando tu API KEY Anónima)
CREATE POLICY "Permitir acceso anonimo" ON public.signals
    FOR ALL
    USING (true)
    WITH CHECK (true);

-- 4. Crear un Índice para que las consultas del MQL5 sean ultrarrápidas
-- Como el EA va a buscar "status=PENDING" constantemente, este índice lo optimiza al 100%
CREATE INDEX idx_signals_status ON public.signals (status);
